version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/usr/src/app
    environment:
      - SUPABASE_URL=https://xyzcompany.supabase.co
      - SUPABASE_KEY=public-anon-key
    depends_on:
      - supabase

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/usr/src/app
    depends_on:
      - backend

  supabase:
    image: supabase/postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=dspot
    volumes:
      - supabase-data:/var/lib/postgresql/data

volumes:
  supabase-data: